apiVersion: v1
kind: Service
metadata:
  name: taxi-calling-service
  labels:
    app: taxi-calling-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: taxi-calling-service