apiVersion: v1
kind: Service
metadata:
  name: driver-management-service
  labels:
    app: driver-management-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: driver-management-service