apiVersion: v1
kind: Service
metadata:
  name: mobile-application-service
  labels:
    app: mobile-application-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mobile-application-service