server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: taxi-calling-service
          uri: http://localhost:8082
          predicates:
            - Path=/taxiCalls/**, /rides/**, /payments/**, /reviews/**, 
        - id: driver-management-service
          uri: http://localhost:8083
          predicates:
            - Path=/drivers/**, 
        - id: mobile-application-service
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: location-service
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: taxi-calling-service
          uri: http://taxiCallingService:8080
          predicates:
            - Path=/taxiCalls/**, /rides/**, /payments/**, /reviews/**, 
        - id: driver-management-service
          uri: http://driverManagementService:8080
          predicates:
            - Path=/drivers/**, 
        - id: mobile-application-service
          uri: http://mobileApplicationService:8080
          predicates:
            - Path=, 
        - id: payment-service
          uri: http://paymentService:8080
          predicates:
            - Path=, 
        - id: location-service
          uri: http://locationService:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
