---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-calling-service
  labels:
    app: taxi-calling-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-calling-service
  template:
    metadata:
      labels:
        app: taxi-calling-service
    spec:
      containers:
        - name: taxi-calling-service
          image: username/taxi-calling-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-management-service
  labels:
    app: driver-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-management-service
  template:
    metadata:
      labels:
        app: driver-management-service
    spec:
      containers:
        - name: driver-management-service
          image: username/driver-management-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-application-service
  labels:
    app: mobile-application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-application-service
  template:
    metadata:
      labels:
        app: mobile-application-service
    spec:
      containers:
        - name: mobile-application-service
          image: username/mobile-application-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: username/payment-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: username/location-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: taxi-calling-service
  labels:
    app: taxi-calling-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: taxi-calling-service


---


apiVersion: v1
kind: Service
metadata:
  name: driver-management-service
  labels:
    app: driver-management-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: driver-management-service


---


apiVersion: v1
kind: Service
metadata:
  name: mobile-application-service
  labels:
    app: mobile-application-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mobile-application-service


---


apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payment-service


---


apiVersion: v1
kind: Service
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: location-service

